version: '2'

services:

  minio1:
    image: minio/minio
    networks:
      - common
    hostname: minio1
    volumes:
      - data1:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data

  localspark1:
    build:
      context: ./spark_s3
    networks:
      - common
    hostname: localspark1 
    ports:
      - "8888:8888"
    command: jupyter notebook --allow-root --no-browser --ip=0.0.0.0 --NotebookApp.token='' --NotebookApp.password=''


networks:
  common:

volumes:
  data1:
